bot:
  name:
    fake_invest_bot
  token: 6452009533:AAF0yecYWj78cHuCsH77J--XLzT048k_bDM
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/investBotDB
    username: postgres
    password: 5123
hibernate:
  default_schema: public